import { useEffect, useState } from 'react'
import './App.css'
import './Thread.css'
import { supabase } from './lib/supabaseClient'
import { isSupabaseConfigured } from './lib/supabase'
import type { User } from '@supabase/supabase-js'

type Tab = 'home' | 'discussions' | 'trips' | 'albums' | 'profile'
type Thread = { id?: string; title: string; body: string; author: string; time: string; replies: number; tone: string; pinned?: boolean }

const initialThreads: Thread[] = []

function setThreadsFromDatabase(rows: Array<{ id: string; title: string; created_at: string; pinned: boolean; posts?: Array<{ content: string }> }>) {
  return rows.map((row, index) => ({ id: row.id, title: row.title, body: row.posts?.[0]?.content ?? '尚無內容', author: '家庭成員', time: index === 0 ? '最新' : '較早', replies: row.posts?.length ?? 0, tone: index % 2 ? 'forest' : 'coral', pinned: row.pinned }))
}

function App() {
  const [tab, setTab] = useState<Tab>('home')
  const [threads, setThreads] = useState<Thread[]>(initialThreads)
  const [draft, setDraft] = useState('')
  const [compose, setCompose] = useState(false)
  const [toast, setToast] = useState('')
  const [profilePanel, setProfilePanel] = useState(false)
  const [authOpen, setAuthOpen] = useState(false)
  const [authMode, setAuthMode] = useState<'login' | 'signup'>('login')
  const [email, setEmail] = useState('')
  const [password, setPassword] = useState('')
  const [displayName, setDisplayName] = useState('')
  const [familyName, setFamilyName] = useState('')
  const [authBusy, setAuthBusy] = useState(false)
  const [sessionEmail, setSessionEmail] = useState<string | null>(null)
  const [sessionName, setSessionName] = useState('')
  useEffect(() => { if (!supabase) return; const applyUser = async (current: User | null) => { setSessionEmail(current?.email ?? null); if (!current) { setSessionName(''); return } const profile = await supabase.from('profiles').select('display_name').eq('id', current.id).maybeSingle(); setSessionName(profile.data?.display_name ?? String(current.user_metadata?.display_name ?? current.email?.split('@')[0] ?? '')) }; supabase.auth.getSession().then(({ data }) => applyUser(data.session?.user ?? null)); const { data } = supabase.auth.onAuthStateChange((_event, current) => { applyUser(current) }); return () => data.subscription.unsubscribe() }, [])
  useEffect(() => { if (!supabase || !sessionEmail) return; supabase.from('threads').select('id,title,created_at,pinned,posts(content,created_at)').order('created_at', { ascending: false }).then(({ data, error }) => { if (error || !data) return; setThreads(setThreadsFromDatabase(data as Array<{ id: string; title: string; created_at: string; pinned: boolean; posts?: Array<{ content: string }> }>)) }) }, [sessionEmail])
  const notify = (message: string) => { setToast(message); window.setTimeout(() => setToast(''), 2400) }
  const submitAuth = async () => { if (!supabase || !email.trim() || !password) return; setAuthBusy(true); const result = authMode === 'login' ? await supabase.auth.signInWithPassword({ email: email.trim(), password }) : await supabase.auth.signUp({ email: email.trim(), password, options: { data: { display_name: displayName.trim() } } }); if (result.error) notify(result.error.message); else if (authMode === 'signup' && result.data.user && displayName.trim() && familyName.trim()) { const bootstrap = await supabase.rpc('bootstrap_family', { p_name: familyName.trim(), p_invite_code: '', p_display_name: displayName.trim() }); if (bootstrap.error) notify(bootstrap.error.message); else notify('註冊成功，家庭空間已建立') } else notify(authMode === 'login' ? '登入成功' : '註冊成功'); setAuthBusy(false); if (!result.error && result.data.user) { setSessionEmail(result.data.user.email ?? email.trim()); setSessionName(displayName.trim() || String(result.data.user.user_metadata?.display_name ?? email.trim().split('@')[0])); setAuthOpen(false); setCompose(false); setProfilePanel(false); setTab('home') } }
  const signOut = async () => { if (supabase) await supabase.auth.signOut(); setProfilePanel(false); notify('已登出') }
  const openComposer = () => { if (!supabase) { notify('尚未連接 Supabase，暫時無法建立內容'); return } if (!sessionEmail) { setAuthOpen(true); return } setCompose(true) }
  const saveProfile = async (name: string) => { if (!supabase) { notify('預覽模式：尚未連接資料庫'); return } const { data: { user } } = await supabase.auth.getUser(); if (!user) { setAuthOpen(true); return } const { error } = await supabase.from('profiles').update({ display_name: name.trim() }).eq('id', user.id); notify(error ? error.message : '個人資料已儲存') }
  const addThread = async () => { if (!supabase || !sessionEmail) { notify('請先登入會員並連接 Supabase'); return } if (!draft.trim()) return; const { data: { user } } = await supabase.auth.getUser(); if (!user) { notify('登入狀態已失效'); return } const { data: profile, error: profileError } = await supabase.from('profiles').select('family_id').eq('id', user.id).maybeSingle(); if (profileError || !profile?.family_id) { notify('尚未加入家庭，請重新註冊建立家庭'); return } const { data: thread, error } = await supabase.from('threads').insert({ family_id: profile.family_id, title: draft.trim(), created_by: user.id }).select('id').single(); if (error || !thread) { notify(error?.message ?? '討論建立失敗'); return } const post = await supabase.from('posts').insert({ thread_id: thread.id, author_id: user.id, content: draft.trim() }); if (post.error) { notify(post.error.message); return } setDraft(''); setCompose(false); notify('討論已分享給家人'); const refreshed = await supabase.from('threads').select('id,title,created_at,pinned,posts(content,created_at)').order('created_at', { ascending: false }); if (refreshed.data) setThreads(setThreadsFromDatabase(refreshed.data as Array<{ id: string; title: string; created_at: string; pinned: boolean; posts?: Array<{ content: string }> }>)) }
  const titles: Record<Tab, string> = { home: '我們的小天地', discussions: '家庭討論', trips: '下一段旅程', albums: '共享相簿', profile: '你的個人檔案' }
  const glyphs: Record<Tab, string> = { home: '◌', discussions: '▤', trips: '↗', albums: '▦', profile: '◎' }
  return <div className="app-shell">
    <aside className="rail"><div className="brand-mark">吾</div><div className="family-switcher"><div className="avatar avatar-small">吾</div><div><b>吾黨所鍾</b><small>我們的家庭空間</small></div><span>⌄</span></div><nav>{(['home','discussions','trips','albums'] as Tab[]).map((item) => <Nav key={item} active={tab === item} label={{ home: '首頁', discussions: '討論', trips: '行程', albums: '相簿' }[item]} glyph={glyphs[item]} onClick={() => setTab(item)} />)}</nav><div className="rail-bottom"><button className="nav-button" onClick={() => setProfilePanel(true)}><span className="nav-glyph">◎</span>設定</button>{sessionEmail && <button className="profile-chip" onClick={() => setTab('profile')}><div className="avatar">{(sessionName || '你')[0]}</div><span>{sessionName || '會員'}</span><span>•••</span></button>}</div></aside>
    <main className="main-canvas"><header className="topbar"><div className="mobile-brand"><div className="brand-mark">吾</div><b>吾黨所鍾</b></div><div className="breadcrumb"><span>吾黨所鍾</span><span>/</span><b>{titles[tab]}</b></div><div className="top-actions"><button className="icon-button" onClick={() => notify('搜尋功能已準備好')} aria-label="搜尋">⌕</button><button className="icon-button" onClick={() => notify('你已掌握最新消息')} aria-label="通知">◌<i /></button><button className="mobile-avatar avatar" onClick={() => setTab('profile')}>訪</button></div></header><div className="content-wrap">
      {tab === 'home' && <Home threads={threads} setTab={setTab} compose={openComposer} sessionName={sessionName} />}
      {tab === 'discussions' && <Discussions threads={threads} compose={openComposer} notify={notify} canPost={Boolean(sessionEmail || !supabase)} />}
      {tab === 'trips' && <Trips notify={notify} />}
      {tab === 'albums' && <Albums notify={notify} />}
      {tab === 'profile' && <Profile notify={notify} saveProfile={saveProfile} />}
    </div></main><nav className="mobile-nav">{(['home','discussions','trips','albums'] as Tab[]).map((item) => <Nav key={item} active={tab === item} label={{ home: '首頁', discussions: '交流', trips: '行程', albums: '相簿' }[item]} glyph={glyphs[item]} onClick={() => setTab(item)} />)}</nav>
    {compose && <div className="modal-backdrop" onMouseDown={() => setCompose(false)}><section className="composer-modal" onMouseDown={(e) => e.stopPropagation()}><p className="eyebrow">新增討論</p><h2>最近有什麼想分享？</h2><textarea autoFocus value={draft} onChange={(e) => setDraft(e.target.value)} placeholder="分享一則留言、一個問題，或一件小小的好事……" /><div className="modal-actions"><button className="button ghost" onClick={() => setCompose(false)}>取消</button><button className="button primary" disabled={!draft.trim()} onClick={addThread}>分享給家人</button></div></section></div>}
    {profilePanel && <div className="modal-backdrop" onMouseDown={() => setProfilePanel(false)}><section className="quick-panel" onMouseDown={(e) => e.stopPropagation()}><button className="close-button" onClick={() => setProfilePanel(false)}>×</button><div className="avatar avatar-large">{sessionName ? sessionName[0] : '訪'}</div><p className="eyebrow">你的空間</p><h2>{sessionEmail ? '已登入' : isSupabaseConfigured ? '尚未登入' : '預覽模式'}</h2><p className="muted">{sessionEmail ?? (isSupabaseConfigured ? 'Supabase 已連接，登入後即可使用會員功能' : '尚未連接 Supabase')}</p>{sessionEmail ? <button className="button ghost full" onClick={signOut}>登出</button> : <button className="button primary full" onClick={() => { setProfilePanel(false); setAuthOpen(true) }}>登入／註冊</button>}<button className="button ghost full" onClick={() => { setProfilePanel(false); setTab('profile') }}>開啟個人檔案</button></section></div>}
    {authOpen && <div className="modal-backdrop" onMouseDown={() => setAuthOpen(false)}><section className="composer-modal" onMouseDown={(e) => e.stopPropagation()}><button className="close-button" onClick={() => setAuthOpen(false)}>×</button><p className="eyebrow">家庭會員</p><h2>{authMode === 'login' ? '登入你的家庭空間' : '建立家庭帳號'}</h2>{authMode === 'signup' && <><input className="auth-input" value={displayName} onChange={(e) => setDisplayName(e.target.value)} placeholder="顯示名稱" /><input className="auth-input" value={familyName} onChange={(e) => setFamilyName(e.target.value)} placeholder="家庭名稱" /></>}<input className="auth-input" type="email" value={email} onChange={(e) => setEmail(e.target.value)} placeholder="電子信箱" /><input className="auth-input" type="password" value={password} onChange={(e) => setPassword(e.target.value)} placeholder="密碼" /><button className="button primary full" disabled={authBusy || !email || !password || (authMode === 'signup' && (!displayName || !familyName))} onClick={submitAuth}>{authBusy ? '處理中……' : authMode === 'login' ? '登入' : '註冊'}</button><button className="text-button full" onClick={() => setAuthMode(authMode === 'login' ? 'signup' : 'login')}>{authMode === 'login' ? '還沒有帳號？註冊' : '已有帳號？登入'}</button></section></div>}
    {toast && <div className="toast" role="status">{toast}<span>✓</span></div>}
  </div>
}

function Nav({ active, label, glyph, onClick, badge }: { active: boolean; label: string; glyph: string; onClick: () => void; badge?: string }) { return <button className={`nav-button ${active ? 'active' : ''}`} onClick={onClick}><span className="nav-glyph">{glyph}</span><span>{label}</span>{badge && <em>{badge}</em>}</button> }
function Hero({ kicker, title, copy, action }: { kicker: string; title: string; copy: string; action?: React.ReactNode }) { return <section className="hero-row"><div><p className="eyebrow">{kicker}</p><h1>{title}<span>.</span></h1><p className="hero-copy">{copy}</p></div>{action}</section> }
function Home({ threads, setTab, compose, sessionName }: { threads: Thread[]; setTab: (t: Tab) => void; compose: () => void; sessionName: string }) { return <><Hero kicker="家庭空間" title={sessionName ? `你好啊！${sessionName}` : '歡迎來到吾黨所鍾'} copy="登入後，這裡會顯示家人的真實動態。" action={<button className="button primary" onClick={compose}>＋ 發起討論</button>} /><section className="feature-grid"><article className="feature-card trip-card"><p className="eyebrow light">行程</p><h2>還沒有行程</h2><p>建立第一個家庭行程，開始一起規劃。</p><button className="text-button light-text" onClick={() => setTab('trips')}>前往行程 →</button></article><article className="feature-card note-card"><p className="eyebrow">家庭留言</p><blockquote>這裡會放家人分享的訊息。</blockquote></article></section><section className="section-heading"><div><p className="eyebrow">最新消息</p><h2>家人動態</h2></div><button className="text-button" onClick={() => setTab('discussions')}>查看討論 →</button></section><div className="empty-state">{threads.length ? threads.slice(0,3).map((thread) => <ThreadCard key={thread.title} thread={thread} onClick={() => setTab('discussions')} />) : <p>目前還沒有討論，成為第一個分享的人吧。</p>}</div><section className="section-heading"><div><p className="eyebrow">回憶</p><h2>共享相簿</h2></div><button className="text-button" onClick={() => setTab('albums')}>查看相簿 →</button></section><div className="empty-state"><p>目前還沒有相簿。</p></div></> }
function Discussions({ threads, compose, notify, canPost }: { threads: Thread[]; compose: () => void; notify: (m: string) => void; canPost: boolean }) { const [selected, setSelected] = useState<Thread | null>(null); const [comment, setComment] = useState(''); const [comments, setComments] = useState<string[]>([]); const addComment = () => { if (!canPost) { notify('請先登入會員再留言'); return } if (!comment.trim()) return; setComments([...comments, comment.trim()]); setComment(''); notify('留言已加入討論') }; return <><Hero kicker="家庭留言板" title="一起聊聊" copy="問題、想法，以及值得記住的每件小事。" action={<button className="button primary" onClick={compose}>＋ 發起討論</button>} /><div className="filter-row"><button className="filter active">全部貼文</button><button className="filter">置頂</button><button className="filter">我的貼文</button><span /><button className="icon-button" onClick={() => notify('篩選功能已準備好')}>≡</button></div><div className="thread-list expanded">{threads.map((thread) => <ThreadCard key={thread.title} thread={thread} onClick={() => setSelected(thread)} />)}</div>{selected && <div className="modal-backdrop" onMouseDown={() => setSelected(null)}><section className="thread-modal" onMouseDown={(e) => e.stopPropagation()}><button className="close-button" onClick={() => setSelected(null)}>×</button><div className={`thread-marker ${selected.tone}`}>{selected.author[0]}</div><p className="eyebrow">{selected.author} · {selected.time}</p><h2>{selected.title}</h2><p className="modal-body">{selected.body}</p><div className="comment-stack">{comments.map((item) => <p key={item}><b>你</b>{item}</p>)}</div><div className="comment-box"><input disabled={!canPost} value={comment} onChange={(e) => setComment(e.target.value)} onKeyDown={(e) => e.key === 'Enter' && addComment()} placeholder={canPost ? '寫下你的想法……' : '登入後即可留言'} /><button className="button primary" onClick={addComment}>回覆</button></div></section></div>}</> }
function ThreadCard({ thread, onClick }: { thread: Thread; onClick: () => void }) { return <article className="thread-card" onClick={onClick} tabIndex={0} onKeyDown={(e) => e.key === 'Enter' && onClick()}><div className={`thread-marker ${thread.tone}`}>{thread.author[0]}</div><div className="thread-body"><div className="thread-meta">{thread.author} · {thread.time}{thread.pinned && <b className="pinned">置頂</b>}</div><h3>{thread.title}</h3><p>{thread.body}</p><div className="thread-footer">□ {thread.replies} 則回覆 <span>↗</span></div></div></article> }
function Trips({ notify }: { notify: (m: string) => void }) { return <><Hero kicker="家庭行程" title="一起規劃下一站" copy="建立屬於家人的第一段旅程。" action={<button className="button primary" onClick={() => notify('請從資料庫建立行程')}>＋ 新增行程</button>} /><div className="empty-state"><p>目前沒有行程資料。</p></div></> }
function Albums({ notify }: { notify: (m: string) => void }) { return <><Hero kicker="共享相簿" title="收藏小日子" copy="把家人想留下的每個時刻放在一起。" action={<button className="button primary" onClick={() => notify('請從資料庫建立相簿')}>＋ 新增相簿</button>} /><div className="empty-state"><p>目前沒有相簿資料。</p></div></> }
function Profile({ notify, saveProfile }: { notify: (m: string) => void; saveProfile: (name: string) => void }) { const [name, setName] = useState(''); return <><section className="profile-hero"><div className="avatar avatar-profile">{name ? name[0] : '訪'}</div><div><p className="eyebrow">你的個人檔案</p><h1>{name || '尚未登入'}<span>.</span></h1><p className="hero-copy">登入後即可編輯你的個人資料。</p></div></section><div className="profile-grid"><section className="setting-card"><p className="eyebrow">個人資料</p><label>顯示名稱<input value={name} onChange={(e) => setName(e.target.value)} placeholder="登入後設定名稱" /></label><button className="button primary" onClick={() => saveProfile(name)}>儲存變更</button></section><section className="setting-card accent"><p className="eyebrow">家庭資料</p><h3>尚無資料</h3><p className="muted">登入並加入家庭後，這裡會顯示家庭資訊。</p><button className="text-button" onClick={() => notify('請先登入會員')}>登入會員 ↗</button></section></div></> }

export default App
