import { useState } from 'react'
import './App.css'

type Tab = 'home' | 'discussions' | 'trips' | 'albums' | 'profile'
type Thread = { title: string; body: string; author: string; time: string; replies: number; tone: string; pinned?: boolean }

const initialThreads: Thread[] = [
  { title: 'Summer in Hualien — where should we stop?', body: 'I mapped a slower route along the coast. Add your must-see places here.', author: 'Maya', time: '18 min ago', replies: 8, tone: 'coral', pinned: true },
  { title: 'Sunday dinner: hand-pulled noodles', body: 'I found a tiny place near the station. Booking for 6:30?', author: 'Leo', time: 'Yesterday', replies: 4, tone: 'forest' },
  { title: 'Grandma’s garden photos', body: 'Uploading the spring set this weekend — tell me which ones to print.', author: 'Nora', time: '2 days ago', replies: 12, tone: 'ochre' },
]
const photos = ['Qixingtan', 'Garden morning', 'Train windows', 'Family table', 'Liyu Lake', 'Rainy afternoon']

function App() {
  const [tab, setTab] = useState<Tab>('home')
  const [threads, setThreads] = useState(initialThreads)
  const [draft, setDraft] = useState('')
  const [compose, setCompose] = useState(false)
  const [toast, setToast] = useState('')
  const [profilePanel, setProfilePanel] = useState(false)
  const notify = (message: string) => { setToast(message); window.setTimeout(() => setToast(''), 2400) }
  const addThread = () => { if (!draft.trim()) return; setThreads([{ title: draft.trim(), body: 'Newly shared with the family. Start the conversation here.', author: 'You', time: 'Just now', replies: 0, tone: 'clay' }, ...threads]); setDraft(''); setCompose(false); notify('Thread shared with the family') }
  const titles: Record<Tab, string> = { home: 'A little room for us', discussions: 'Family discussions', trips: 'The next chapter', albums: 'Shared albums', profile: 'Your profile' }
  const glyphs: Record<Tab, string> = { home: '◌', discussions: '▤', trips: '↗', albums: '▦', profile: '◎' }
  return <div className="app-shell">
    <aside className="rail"><div className="brand-mark">k</div><div className="family-switcher"><div className="avatar avatar-small">K</div><div><b>Kinfolk</b><small>Our family space</small></div><span>⌄</span></div><nav>{(['home','discussions','trips','albums'] as Tab[]).map((item) => <Nav key={item} active={tab === item} label={item === 'discussions' ? 'Discussions' : item[0].toUpperCase() + item.slice(1)} glyph={glyphs[item]} onClick={() => setTab(item)} badge={item === 'discussions' ? '3' : undefined} />)}</nav><div className="rail-bottom"><button className="nav-button" onClick={() => setProfilePanel(true)}><span className="nav-glyph">◎</span>Settings</button><button className="profile-chip" onClick={() => setTab('profile')}><div className="avatar">M</div><span>Maya Chen</span><span>•••</span></button></div></aside>
    <main className="main-canvas"><header className="topbar"><div className="mobile-brand"><div className="brand-mark">k</div><b>Kinfolk</b></div><div className="breadcrumb"><span>Kinfolk</span><span>/</span><b>{titles[tab]}</b></div><div className="top-actions"><button className="icon-button" onClick={() => notify('Search is ready')} aria-label="Search">⌕</button><button className="icon-button" onClick={() => notify('You are all caught up')} aria-label="Notifications">◌<i /></button><button className="mobile-avatar avatar" onClick={() => setTab('profile')}>M</button></div></header><div className="content-wrap">
      {tab === 'home' && <Home threads={threads} setTab={setTab} compose={() => setCompose(true)} notify={notify} />}
      {tab === 'discussions' && <Discussions threads={threads} compose={() => setCompose(true)} notify={notify} />}
      {tab === 'trips' && <Trips notify={notify} />}
      {tab === 'albums' && <Albums notify={notify} />}
      {tab === 'profile' && <Profile notify={notify} />}
    </div></main><nav className="mobile-nav">{(['home','discussions','trips','albums'] as Tab[]).map((item) => <Nav key={item} active={tab === item} label={item === 'discussions' ? 'Talk' : item[0].toUpperCase() + item.slice(1)} glyph={glyphs[item]} onClick={() => setTab(item)} />)}</nav>
    {compose && <div className="modal-backdrop" onMouseDown={() => setCompose(false)}><section className="composer-modal" onMouseDown={(e) => e.stopPropagation()}><p className="eyebrow">NEW DISCUSSION</p><h2>What’s on your mind?</h2><textarea autoFocus value={draft} onChange={(e) => setDraft(e.target.value)} placeholder="Share a note, a question, or a small win…" /><div className="modal-actions"><button className="button ghost" onClick={() => setCompose(false)}>Cancel</button><button className="button primary" disabled={!draft.trim()} onClick={addThread}>Share with family</button></div></section></div>}
    {profilePanel && <div className="modal-backdrop" onMouseDown={() => setProfilePanel(false)}><section className="quick-panel" onMouseDown={(e) => e.stopPropagation()}><button className="close-button" onClick={() => setProfilePanel(false)}>×</button><div className="avatar avatar-large">M</div><p className="eyebrow">YOUR SPACE</p><h2>Maya Chen</h2><p className="muted">maya@example.com</p><button className="button primary full" onClick={() => { setProfilePanel(false); setTab('profile') }}>Open profile</button><button className="button ghost full" onClick={() => notify('Invite link copied')}>Copy invite link</button></section></div>}
    {toast && <div className="toast" role="status">{toast}<span>✓</span></div>}
  </div>
}

function Nav({ active, label, glyph, onClick, badge }: { active: boolean; label: string; glyph: string; onClick: () => void; badge?: string }) { return <button className={`nav-button ${active ? 'active' : ''}`} onClick={onClick}><span className="nav-glyph">{glyph}</span><span>{label}</span>{badge && <em>{badge}</em>}</button> }
function Hero({ kicker, title, copy, action }: { kicker: string; title: string; copy: string; action?: React.ReactNode }) { return <section className="hero-row"><div><p className="eyebrow">{kicker}</p><h1>{title}<span>.</span></h1><p className="hero-copy">{copy}</p></div>{action}</section> }
function Home({ threads, setTab, compose, notify }: { threads: Thread[]; setTab: (t: Tab) => void; compose: () => void; notify: (m: string) => void }) { return <><Hero kicker="THURSDAY, AUGUST 08" title="Good morning, Maya" copy="A quiet place for the people you call home." action={<button className="button primary" onClick={compose}>＋ Start a discussion</button>} /><section className="feature-grid"><article className="feature-card trip-card"><p className="eyebrow light">UP NEXT <span className="card-arrow">↗</span></p><div className="trip-title"><span className="date-stamp">14<small>AUG</small></span><div><h2>Hualien, slowly</h2><p>Aug 14 — Aug 18 · 6 people</p></div></div><div className="route-line"><i /><b /><i /></div><div className="route-labels"><span>Taipei</span><span>East coast</span></div><button className="text-button light-text" onClick={() => setTab('trips')}>Open itinerary →</button></article><article className="feature-card note-card"><p className="eyebrow">A NOTE FROM LEO <span className="avatar avatar-tiny">L</span></p><blockquote>“The best plans are the ones that leave room for a good detour.”</blockquote><div className="note-footer"><span>Shared 2 hours ago</span><button className="text-button" onClick={() => notify('Note saved')}>Save note ↗</button></div></article></section><section className="section-heading"><div><p className="eyebrow">THE LATEST</p><h2>From the family</h2></div><button className="text-button" onClick={() => setTab('discussions')}>See all discussions →</button></section><div className="thread-list">{threads.slice(0,3).map((thread) => <ThreadCard key={thread.title} thread={thread} onClick={() => setTab('discussions')} />)}</div><section className="section-heading"><div><p className="eyebrow">MEMORIES</p><h2>Recent albums</h2></div><button className="text-button" onClick={() => setTab('albums')}>View albums →</button></section><div className="photo-strip">{photos.slice(0,4).map((photo, i) => <button key={photo} className={`photo-tile tile-${i}`} onClick={() => setTab('albums')}><span>{photo}</span></button>)}</div></> }
function Discussions({ threads, compose, notify }: { threads: Thread[]; compose: () => void; notify: (m: string) => void }) { return <><Hero kicker="THE FAMILY BOARD" title="Conversations" copy="Questions, ideas, and the things worth remembering." action={<button className="button primary" onClick={compose}>＋ Start a discussion</button>} /><div className="filter-row"><button className="filter active">All posts</button><button className="filter">Pinned</button><button className="filter">My posts</button><span /><button className="icon-button" onClick={() => notify('Filters are ready')}>≡</button></div><div className="thread-list expanded">{threads.map((thread) => <ThreadCard key={thread.title} thread={thread} onClick={() => notify(`Opening “${thread.title}”`)} />)}</div></> }
function ThreadCard({ thread, onClick }: { thread: Thread; onClick: () => void }) { return <article className="thread-card" onClick={onClick} tabIndex={0} onKeyDown={(e) => e.key === 'Enter' && onClick()}><div className={`thread-marker ${thread.tone}`}>{thread.author[0]}</div><div className="thread-body"><div className="thread-meta">{thread.author} · {thread.time}{thread.pinned && <b className="pinned">PINNED</b>}</div><h3>{thread.title}</h3><p>{thread.body}</p><div className="thread-footer">□ {thread.replies} {thread.replies === 1 ? 'reply' : 'replies'} <span>↗</span></div></div></article> }
function Trips({ notify }: { notify: (m: string) => void }) { const days = [['01','Aug 14','Arrive in Hualien',['Pick up the rental car','Check in at the coast house']],['02','Aug 15','The green valley',['Breakfast at Qixingtan','Walk the Liyu Lake trail']],['03','Aug 16','Slow morning',['Market run','Picnic by the river']]]; return <><Hero kicker="AUGUST 14 — 18, 2024" title="Hualien, slowly" copy="A five-day pocket of green, sea, and unhurried mornings." action={<button className="button primary" onClick={() => notify('New day added')}>＋ Add a day</button>} /><div className="itinerary-list">{days.map(([num,date,title,items]) => <article className="day-card" key={String(num)}><div className="day-number">{num}</div><div className="day-content"><div className="day-heading"><div><p className="eyebrow">{date}</p><h3>{title}</h3></div><button className="icon-button small" onClick={() => notify('Day options opened')}>•••</button></div><div className="day-items">{(items as string[]).map((item) => <button className="day-item" key={item} onClick={() => notify(`Opened ${item}`)}><i />{item}<span>→</span></button>)}</div><button className="add-item" onClick={() => notify('Add an itinerary item')}>＋ Add item</button></div></article>)}</div></> }
function Albums({ notify }: { notify: (m: string) => void }) { return <><Hero kicker="6 ALBUMS · 148 PHOTOS" title="Little archives" copy="The ordinary moments we want to keep close." action={<button className="button primary" onClick={() => notify('Create album flow opened')}>＋ New album</button>} /><div className="album-grid">{photos.map((photo, i) => <button className={`album-card tile-${i}`} key={photo} onClick={() => notify(`Opening ${photo}`)}><div className="album-art"><span>{12 + i * 7} photos</span></div><div className="album-caption"><b>{photo}</b><small>Shared by family</small></div></button>)}</div></> }
function Profile({ notify }: { notify: (m: string) => void }) { return <><section className="profile-hero"><div className="avatar avatar-profile">M</div><div><p className="eyebrow">YOUR PROFILE</p><h1>Maya Chen<span>.</span></h1><p className="hero-copy">The one who keeps everyone moving.</p></div><button className="button ghost" onClick={() => notify('Profile editing is ready')}>Edit profile</button></section><div className="profile-grid"><section className="setting-card"><p className="eyebrow">PERSONAL DETAILS</p><label>Display name<input defaultValue="Maya Chen" /></label><label>Email address<input defaultValue="maya@example.com" /></label><button className="button primary" onClick={() => notify('Profile saved')}>Save changes</button></section><section className="setting-card accent"><p className="eyebrow">YOUR FAMILY</p><h3>Kinfolk</h3><p className="muted">6 members · Joined March 2023</p><button className="text-button" onClick={() => notify('Invite link copied')}>Copy invite link ↗</button></section></div></> }

export default App
