import { useEffect, useState } from 'react'
import './App.css'
import './Thread.css'
import { supabase } from './lib/supabaseClient'
import { isSupabaseConfigured } from './lib/supabase'
import type { User } from '@supabase/supabase-js'

type Tab = 'home' | 'discussions' | 'trips' | 'albums'
type Thread = { id?: string; title: string; body: string; author: string; authorId?: string; time: string; replies: number; tone: string; pinned?: boolean }

function logSupabaseError(operation: string, error: { message?: string; code?: string; details?: string; hint?: string } | null | undefined) {
  if (!error) return
  console.error(`[吾黨所鍾][Supabase][${operation}]`, { code: error.code, message: error.message, details: error.details, hint: error.hint })
}

const initialThreads: Thread[] = []

function setThreadsFromDatabase(rows: Array<{ id: string; title: string; created_at: string; pinned: boolean; created_by?: string; posts?: Array<{ content: string }> }>) {
  return rows.map((row, index) => ({ id: row.id, title: row.title, body: row.posts?.[0]?.content ?? '尚無內容', author: '家庭成員', authorId: row.created_by, time: index === 0 ? '最新' : '較早', replies: row.posts?.length ?? 0, tone: index % 2 ? 'forest' : 'coral', pinned: row.pinned }))
}

function App() {
  const [tab, setTab] = useState<Tab | 'profile'>('home')
  const [threads, setThreads] = useState<Thread[]>(initialThreads)
  const [draft, setDraft] = useState('')
  const [compose, setCompose] = useState(false)
  const [toast, setToast] = useState('')
  const [profilePanel, setProfilePanel] = useState(false)
  const [authOpen, setAuthOpen] = useState(false)
  const [authMode, setAuthMode] = useState<'login' | 'signup'>('login')
  const [email, setEmail] = useState('')
  const [password, setPassword] = useState('')
  const [displayName, setDisplayName] = useState('')
  const [authBusy, setAuthBusy] = useState(false)
  const [sessionEmail, setSessionEmail] = useState<string | null>(null)
  const [sessionName, setSessionName] = useState('')
  const [sessionUserId, setSessionUserId] = useState<string | null>(null)
  const [detailId, setDetailId] = useState<string | null>(() => window.location.pathname.match(/^\/forum\/posts\/([^/]+)/)?.[1] ?? null)
  const [authReady, setAuthReady] = useState(false)
  useEffect(() => { const onPopState = () => { const next = window.location.pathname.match(/^\/forum\/posts\/([^/]+)/)?.[1] ?? null; setDetailId(next); if (!next) setTab('discussions') }; window.addEventListener('popstate', onPopState); return () => window.removeEventListener('popstate', onPopState) }, [])
  useEffect(() => { if (!supabase) { setAuthReady(true); return } const client = supabase; const applyUser = async (current: User | null) => { setSessionEmail(current?.email ?? null); setSessionUserId(current?.id ?? null); if (!current?.id) { setSessionName(''); setAuthReady(true); return } const fallbackName = String(current.email?.split('@')[0] ?? '會員'); let profile = await client.from('profiles').select('display_name').eq('id', current.id).maybeSingle(); logSupabaseError('profiles.select', profile.error); const legacyName = profile.data?.display_name?.trim().toLowerCase() === 'maya chen'; if (!profile.data || legacyName) { const bootstrap = await client.rpc('bootstrap_family', { p_display_name: fallbackName }); logSupabaseError('bootstrap_family', bootstrap.error); if (bootstrap.error) { setAuthReady(true); return } profile = await client.from('profiles').select('display_name').eq('id', current.id).maybeSingle(); logSupabaseError('profiles.select.retry', profile.error) } setSessionName(profile.data?.display_name ?? fallbackName); setAuthReady(true) }; client.auth.getSession().then(({ data, error }) => { logSupabaseError('auth.getSession', error); applyUser(data.session?.user ?? null) }); const { data } = client.auth.onAuthStateChange((_event, session) => { applyUser(session?.user ?? null) }); return () => data.subscription.unsubscribe() }, [])
  useEffect(() => { if (!supabase || !sessionEmail) return; supabase.from('threads').select('id,title,created_at,pinned,created_by,posts(content,created_at)').order('created_at', { ascending: false }).then(({ data, error }) => { if (error || !data) return; setThreads(setThreadsFromDatabase(data as Array<{ id: string; title: string; created_at: string; pinned: boolean; created_by?: string; posts?: Array<{ content: string }> }>)) }) }, [sessionEmail])
  const notify = (message: string) => { setToast(message); window.setTimeout(() => setToast(''), 2400) }
  const submitAuth = async () => { if (!supabase || !email.trim() || !password) return; setAuthBusy(true); const result = authMode === 'login' ? await supabase.auth.signInWithPassword({ email: email.trim(), password }) : await supabase.auth.signUp({ email: email.trim(), password, options: { data: { display_name: displayName.trim(), }, emailRedirectTo: window.location.origin } }); if (result.error) { notify(result.error.message); setAuthBusy(false); return } if (!result.data.user || !result.data.session) { if (authMode === 'signup') { notify('註冊成功，請先到信箱完成驗證，再回來登入'); setAuthMode('login') } else notify('登入未建立工作階段，請重新嘗試'); setAuthBusy(false); return } const memberName = authMode === 'signup' ? displayName.trim() : email.trim().split('@')[0]; const bootstrap = await supabase.rpc('bootstrap_family', { p_display_name: memberName }); if (bootstrap.error) { notify(`會員資料同步失敗：${bootstrap.error.message}`); setAuthBusy(false); return } notify(authMode === 'login' ? '登入成功' : '註冊成功'); setSessionEmail(result.data.user.email ?? email.trim()); setSessionUserId(result.data.user.id); setSessionName(memberName); setAuthOpen(false); setCompose(false); setProfilePanel(false); setTab('home'); setAuthBusy(false) }
  const signOut = async () => { if (supabase) await supabase.auth.signOut(); setSessionEmail(null); setSessionUserId(null); setSessionName(''); setThreads([]); setProfilePanel(false); setTab('home'); notify('已登出') }
  const openComposer = async () => { if (!supabase) { notify('尚未連接 Supabase，暫時無法建立內容'); return } const { data, error } = await supabase.auth.getSession(); logSupabaseError('auth.getSession.composer', error); if (!data.session?.user?.id) { setSessionEmail(null); setSessionName(''); setAuthOpen(true); return } setSessionEmail(data.session.user.email ?? null); setCompose(true) }
  const saveProfile = async (name: string) => { if (!supabase) { notify('預覽模式：尚未連接資料庫'); return } const { data: { user } } = await supabase.auth.getUser(); if (!user) { setAuthOpen(true); return } const nextName = name.trim(); if (!nextName) { notify('請輸入顯示名稱'); return } const { error } = await supabase.from('profiles').update({ display_name: nextName }).eq('id', user.id); if (!error) setSessionName(nextName); notify(error ? error.message : '個人資料已儲存') }
  const addThread = async () => { if (!supabase || !sessionEmail) { notify('請先登入會員並連接 Supabase'); return } if (!draft.trim()) return; const { data: { user } } = await supabase.auth.getUser(); if (!user?.id) { notify('登入狀態已失效'); return } let { data: profile, error: profileError } = await supabase.from('profiles').select('family_id').eq('id', user.id).maybeSingle(); logSupabaseError('profiles.for-post', profileError); if (!profile?.family_id) { const fallbackName = user.email?.split('@')[0] ?? '會員'; const bootstrap = await supabase.rpc('bootstrap_family', { p_display_name: fallbackName }); logSupabaseError('bootstrap_family.for-post', bootstrap.error); if (bootstrap.error) { notify(`會員資料同步失敗：${bootstrap.error.message}`); return } ({ data: profile, error: profileError } = await supabase.from('profiles').select('family_id').eq('id', user.id).maybeSingle()); logSupabaseError('profiles.for-post.retry', profileError) } if (!profile?.family_id) { notify('會員資料尚未同步，請確認資料庫已執行最新 schema.sql'); return } const { data: thread, error } = await supabase.from('threads').insert({ family_id: profile.family_id, title: draft.trim(), created_by: user.id }).select('id').single(); logSupabaseError('threads.insert', error); if (error || !thread) { notify(error?.message ?? '討論建立失敗'); return } const post = await supabase.from('posts').insert({ thread_id: thread.id, user_id: user.id, content: draft.trim() }); logSupabaseError('posts.insert', post.error); if (post.error) { notify(post.error.message); return } setDraft(''); setCompose(false); notify('討論已分享給家人'); const refreshed = await supabase.from('threads').select('id,title,created_at,pinned,posts(content,created_at)').order('created_at', { ascending: false }); logSupabaseError('threads.refresh', refreshed.error); if (refreshed.data) setThreads(setThreadsFromDatabase(refreshed.data as Array<{ id: string; title: string; created_at: string; pinned: boolean; posts?: Array<{ content: string }> }>)) }
  const titles: Record<string, string> = { home: '我們的小天地', discussions: '家庭討論', trips: '下一段旅程', albums: '共享相簿', profile: '你的個人檔案' }
  const glyphs: Record<string, string> = { home: '◌', discussions: '▤', trips: '↗', albums: '▦', profile: '◎' }
  return <div className="app-shell">
    <aside className="rail"><div className="brand-mark">吾</div><div className="family-switcher"><div className="avatar avatar-small">吾</div><div><b>吾黨所鍾</b><small>我們的家庭空間</small></div><span>⌄</span></div><nav>{(['home','discussions','trips','albums'] as Tab[]).map((item) => <Nav key={item} active={tab === item} label={{ home: '首頁', discussions: '討論', trips: '行程', albums: '相簿' }[item]} glyph={glyphs[item]} onClick={() => setTab(item)} />)}</nav><div className="rail-bottom"><button className="nav-button" onClick={() => setProfilePanel(true)}><span className="nav-glyph">◎</span>設定</button>{sessionEmail && <button className="profile-chip" onClick={() => setTab('profile')}><div className="avatar">{(sessionName || '你')[0]}</div><span>{sessionName || '會員'}</span><span>•••</span></button>}</div></aside>
    <main className="main-canvas"><header className="topbar"><div className="mobile-brand"><div className="brand-mark">吾</div><b>吾黨所鍾</b></div><div className="breadcrumb"><span>吾黨所鍾</span><span>/</span><b>{titles[tab]}</b></div><div className="top-actions"><button className="icon-button" onClick={() => notify('搜尋功能已準備好')} aria-label="搜尋">⌕</button><button className="icon-button" onClick={() => notify('你已掌握最新消息')} aria-label="通知">◌<i /></button>{!authReady ? <span className="muted">載入中…</span> : sessionEmail ? <><button className="button ghost account-button" onClick={() => setProfilePanel(true)}>{sessionName || '會員資料'}</button><button className="button ghost account-button" onClick={signOut}>登出</button></> : <button className="button primary account-button" onClick={() => setAuthOpen(true)}>登入／註冊</button>}<button className="mobile-avatar avatar" onClick={() => setTab('profile')}>訪</button></div></header><div className="content-wrap">
      {tab === 'home' && <Home threads={threads} setTab={setTab} compose={openComposer} sessionName={sessionName} />}
      {detailId ? <ArticleDetailPage id={detailId} userId={sessionUserId} sessionEmail={sessionEmail} notify={notify} onBack={() => { history.pushState({}, '', '/'); setDetailId(null); setTab('discussions') }} /> : tab === 'discussions' && <Discussions threads={threads} compose={openComposer} notify={notify} onOpen={(id) => { history.pushState({}, '', `/forum/posts/${id}`); setDetailId(id) }} />}
      {tab === 'trips' && <Trips notify={notify} sessionEmail={sessionEmail} />}
      {tab === 'albums' && <Albums notify={notify} sessionEmail={sessionEmail} />}
      {tab === 'profile' && <Profile notify={notify} saveProfile={saveProfile} sessionName={sessionName} sessionEmail={sessionEmail} />}
    </div></main><nav className="mobile-nav">{(['home','discussions','trips','albums'] as Tab[]).map((item) => <Nav key={item} active={tab === item} label={{ home: '首頁', discussions: '交流', trips: '行程', albums: '相簿' }[item]} glyph={glyphs[item]} onClick={() => setTab(item)} />)}</nav>
    {compose && <div className="modal-backdrop" onMouseDown={() => setCompose(false)}><section className="composer-modal" onMouseDown={(e) => e.stopPropagation()}><p className="eyebrow">新增討論</p><h2>最近有什麼想分享？</h2><textarea autoFocus value={draft} onChange={(e) => setDraft(e.target.value)} placeholder="分享一則留言、一個問題，或一件小小的好事……" /><div className="modal-actions"><button className="button ghost" onClick={() => setCompose(false)}>取消</button><button className="button primary" disabled={!draft.trim()} onClick={addThread}>分享給家人</button></div></section></div>}
    {profilePanel && <div className="modal-backdrop" onMouseDown={() => setProfilePanel(false)}><section className="quick-panel" onMouseDown={(e) => e.stopPropagation()}><button className="close-button" onClick={() => setProfilePanel(false)}>×</button><div className="avatar avatar-large">{sessionName ? sessionName[0] : '訪'}</div><p className="eyebrow">你的空間</p><h2>{sessionEmail ? '已登入' : isSupabaseConfigured ? '尚未登入' : '預覽模式'}</h2><p className="muted">{sessionEmail ?? (isSupabaseConfigured ? 'Supabase 已連接，登入後即可使用會員功能' : '尚未連接 Supabase')}</p>{sessionEmail ? <button className="button ghost full" onClick={signOut}>登出</button> : <button className="button primary full" onClick={() => { setProfilePanel(false); setAuthOpen(true) }}>登入／註冊</button>}<button className="button ghost full" onClick={() => { setProfilePanel(false); setTab('profile') }}>開啟個人檔案</button></section></div>}
    {authOpen && <div className="modal-backdrop" onMouseDown={() => setAuthOpen(false)}><section className="composer-modal" onMouseDown={(e) => e.stopPropagation()}><button className="close-button" onClick={() => setAuthOpen(false)}>×</button><p className="eyebrow">吾黨所鍾會員</p><h2>{authMode === 'login' ? '登入家庭空間' : '建立會員帳號'}</h2>{authMode === 'signup' && <input className="auth-input" value={displayName} onChange={(e) => setDisplayName(e.target.value)} placeholder="顯示名稱" />}<input className="auth-input" type="email" value={email} onChange={(e) => setEmail(e.target.value)} placeholder="電子信箱" /><input className="auth-input" type="password" value={password} onChange={(e) => setPassword(e.target.value)} placeholder="密碼" /><button className="button primary full" disabled={authBusy || !email || !password || (authMode === 'signup' && !displayName)} onClick={submitAuth}>{authBusy ? '處理中……' : authMode === 'login' ? '登入' : '註冊'}</button><button className="text-button full" onClick={() => setAuthMode(authMode === 'login' ? 'signup' : 'login')}>{authMode === 'login' ? '還沒有帳號？註冊' : '已有帳號？登入'}</button></section></div>}
    {toast && <div className="toast" role="status">{toast}<span>✓</span></div>}
  </div>
}

function Nav({ active, label, glyph, onClick, badge }: { active: boolean; label?: string; glyph: string; onClick: () => void; badge?: string }) { return <button className={`nav-button ${active ? 'active' : ''}`} onClick={onClick}><span className="nav-glyph">{glyph}</span><span>{label ?? ''}</span>{badge && <em>{badge}</em>}</button> }
function Hero({ kicker, title, copy, action }: { kicker: string; title: string; copy: string; action?: React.ReactNode }) { return <section className="hero-row"><div><p className="eyebrow">{kicker}</p><h1>{title}<span>.</span></h1><p className="hero-copy">{copy}</p></div>{action}</section> }
function Home({ threads, setTab, compose, sessionName }: { threads: Thread[]; setTab: (t: Tab) => void; compose: () => void; sessionName: string }) { return <><Hero kicker="家庭空間" title={sessionName ? `你好啊！${sessionName}` : '歡迎來到吾黨所鍾'} copy="登入後，這裡會顯示家人的真實動態。" action={<button className="button primary" onClick={compose}>＋ 發起討論</button>} /><section className="feature-grid"><article className="feature-card trip-card"><p className="eyebrow light">行程</p><h2>還沒有行程</h2><p>建立第一個家庭行程，開始一起規劃。</p><button className="text-button light-text" onClick={() => setTab('trips')}>前往行程 →</button></article><article className="feature-card note-card"><p className="eyebrow">家庭留言</p><blockquote>這裡會放家人分享的訊息。</blockquote></article></section><section className="section-heading"><div><p className="eyebrow">最新消息</p><h2>家人動態</h2></div><button className="text-button" onClick={() => setTab('discussions')}>查看討論 →</button></section><div className="empty-state">{threads.length ? threads.slice(0,3).map((thread) => <ThreadCard key={thread.title} thread={thread} onClick={() => setTab('discussions')} />) : <p>目前還沒有討論，成為第一個分享的人吧。</p>}</div><section className="section-heading"><div><p className="eyebrow">回憶</p><h2>共享相簿</h2></div><button className="text-button" onClick={() => setTab('albums')}>查看相簿 →</button></section><div className="empty-state"><p>目前還沒有相簿。</p></div></> }
function Discussions({ threads, compose, notify, onOpen }: { threads: Thread[]; compose: () => void; notify: (m: string) => void; onOpen: (id: string) => void }) { return <><Hero kicker="家庭留言板" title="一起聊聊" copy="問題、想法，以及值得記住的每件小事。" action={<button className="button primary" onClick={compose}>＋ 發起討論</button>} /><div className="filter-row"><button className="filter active">全部貼文</button><button className="filter">置頂</button><button className="filter">我的貼文</button><span /><button className="icon-button" onClick={() => notify('篩選功能已準備好')}>≡</button></div><div className="thread-list expanded">{threads.map((thread) => <ThreadCard key={thread.id ?? thread.title} thread={thread} onClick={() => thread.id && onOpen(thread.id)} />)}</div></> }
// Legacy detail implementation retained in history; ArticleDetailPage is the active implementation.
function ArticleDetailPage({ id, userId, sessionEmail, notify, onBack }: { id: string; userId: string | null; sessionEmail: string | null; notify: (m: string) => void; onBack: () => void }) {
  type Reply = { id: string; content: string; created_at: string; user_id: string; author: string }
  const [post, setPost] = useState<{ title: string; content: string; authorId: string; createdAt: string; authorName: string } | null>(null)
  const [replies, setReplies] = useState<Reply[]>([])
  const [loading, setLoading] = useState(true)
  const [editing, setEditing] = useState(false)
  const [title, setTitle] = useState('')
  const [content, setContent] = useState('')
  const [reply, setReply] = useState('')
  const [liveUserId, setLiveUserId] = useState<string | null>(userId)
  const load = async () => {
    if (!supabase) { setLoading(false); return }
    const result = await supabase.from('threads').select('id,title,created_at,created_by,posts(id,content,created_at,user_id)').eq('id', id).maybeSingle()
    logSupabaseError('thread.detail', result.error)
    if (result.error || !result.data) { setLoading(false); return }
    const rows = (result.data.posts ?? []) as Array<{ id: string; content: string; created_at: string; user_id: string }>
    const profileIds = [...new Set([result.data.created_by, ...rows.map(row => row.user_id)])]
    const profiles = await supabase.from('profiles').select('id,display_name').in('id', profileIds)
    logSupabaseError('thread.detail.profiles', profiles.error)
    const names = new Map((profiles.data ?? []).map(profile => [profile.id, profile.display_name || '會員']))
    const first = rows[0]
    if (!first) { setLoading(false); return }
    setPost({ title: result.data.title, content: first.content, authorId: result.data.created_by, createdAt: result.data.created_at, authorName: names.get(result.data.created_by) ?? '會員' })
    setReplies(rows.slice(1).map(row => ({ ...row, author: names.get(row.user_id) ?? '會員' })))
    setTitle(result.data.title); setContent(first.content); setLoading(false)
  }
  useEffect(() => { setLiveUserId(userId); if (supabase) void supabase.auth.getUser().then(({ data }) => setLiveUserId(data.user?.id ?? null)); void load() }, [id, userId])
  const save = async () => {
    if (!supabase || !post || post.authorId !== liveUserId || !liveUserId || !title.trim() || !content.trim()) return
    const threadUpdate = await supabase.from('threads').update({ title: title.trim() }).eq('id', id).eq('created_by', liveUserId)
    logSupabaseError('thread.update', threadUpdate.error)
    if (threadUpdate.error) { notify(threadUpdate.error.message); return }
    const postUpdate = await supabase.from('posts').update({ content: content.trim() }).eq('thread_id', id).eq('user_id', liveUserId)
    logSupabaseError('post.update', postUpdate.error)
    if (postUpdate.error) { notify(postUpdate.error.message); return }
    setPost({ ...post, title: title.trim(), content: content.trim() }); setEditing(false); notify('文章已更新')
  }
  const remove = async () => {
    if (!supabase || !post || post.authorId !== liveUserId || !liveUserId || !window.confirm('確定要刪除這篇文章嗎？刪除後無法復原。')) return
    const result = await supabase.from('threads').delete().eq('id', id).eq('created_by', liveUserId)
    logSupabaseError('thread.delete', result.error)
    if (result.error) notify(result.error.message); else { notify('文章已刪除'); onBack() }
  }
  const addReply = async () => {
    if (!supabase || !liveUserId || !reply.trim()) { notify('登入後才能留言'); return }
    const result = await supabase.from('posts').insert({ thread_id: id, user_id: liveUserId, content: reply.trim() }).select('id,content,created_at,user_id').single()
    logSupabaseError('post.reply', result.error)
    if (result.error || !result.data) { notify(result.error?.message ?? '留言失敗'); return }
    setReplies(current => [...current, { ...result.data, author: '我' }]); setReply(''); notify('留言已發布')
  }
  if (loading) return <div className="empty-state"><p>文章載入中…</p></div>
  if (!post) return <div className="empty-state"><p>找不到這篇文章</p><button className="button ghost" onClick={onBack}>返回討論區</button></div>
  const owner = post.authorId === liveUserId
  return <section className="article-detail"><button className="text-button" onClick={onBack}>← 返回討論區</button><div className="article-layout"><aside className="author-panel"><div className="avatar avatar-large">{post.authorName[0]}</div><h3>{post.authorName}</h3><p className="muted">家庭會員</p><p className="muted">作者 ID：{post.authorId.slice(0, 8)}…</p></aside><article className="article-content"><div className="article-actions">{owner && <><button className="button ghost" onClick={() => setEditing(value => !value)}>編輯文章</button><button className="button ghost danger-button" onClick={remove}>刪除文章</button></>}</div>{editing ? <div className="article-editor"><input className="auth-input" value={title} onChange={event => setTitle(event.target.value)} aria-label="文章標題" /><textarea value={content} onChange={event => setContent(event.target.value)} aria-label="文章內容" /><button className="button primary" onClick={save}>儲存文章</button></div> : <><h1>{post.title}</h1><p className="muted">{new Date(post.createdAt).toLocaleString('zh-TW')}</p><p className="modal-body article-body">{post.content}</p></>}</article></div><div className="comment-stack"><h2>留言／回覆</h2>{replies.length ? replies.map(item => <div className="comment-item" key={item.id}><div className="avatar">{item.author[0]}</div><div><b>{item.author}</b><small>{new Date(item.created_at).toLocaleString('zh-TW')}</small><p>{item.content}</p></div></div>) : <p className="muted">目前還沒有留言。</p>}{sessionEmail ? <div className="comment-box"><input value={reply} onChange={event => setReply(event.target.value)} placeholder="寫下你的留言…" onKeyDown={event => event.key === 'Enter' && void addReply()} /><button className="button primary" onClick={addReply}>留言</button></div> : <p className="muted">登入後即可留言。</p>}</div></section>
}
function ThreadCard({ thread, onClick }: { thread: Thread; onClick: () => void }) { return <article className="thread-card" onClick={onClick} tabIndex={0} onKeyDown={(e) => e.key === 'Enter' && onClick()}><div className={`thread-marker ${thread.tone}`}>{thread.author[0]}</div><div className="thread-body"><div className="thread-meta">{thread.author} · {thread.time}{thread.pinned && <b className="pinned">置頂</b>}</div><h3>{thread.title}</h3><p>{thread.body}</p><div className="thread-footer">□ {thread.replies} 則回覆 <span>↗</span></div></div></article> }
function Trips({ notify, sessionEmail }: { notify: (m: string) => void; sessionEmail: string | null }) { const [items, setItems] = useState<Array<{ id: string; title: string; start_date: string; end_date: string }>>([]); const [title, setTitle] = useState(''); const [start, setStart] = useState(''); const [end, setEnd] = useState(''); const load = async () => { if (!supabase || !sessionEmail) return; const { data } = await supabase.from('itineraries').select('id,title,start_date,end_date').order('start_date'); setItems(data ?? []) }; useEffect(() => { load() }, [sessionEmail]); const create = async () => { if (!supabase || !sessionEmail) { notify('請先登入會員'); return } if (!title.trim() || !start || !end) { notify('請填寫行程名稱與日期'); return } const { data: { user } } = await supabase.auth.getUser(); if (!user) return; const { data: profile } = await supabase.from('profiles').select('family_id').eq('id', user.id).maybeSingle(); if (!profile?.family_id) { notify('會員資料尚未同步'); return } const { error } = await supabase.from('itineraries').insert({ family_id: profile.family_id, title: title.trim(), start_date: start, end_date: end, created_by: user.id }); if (error) notify(error.message); else { setTitle(''); setStart(''); setEnd(''); notify('行程已建立'); load() } }; return <><Hero kicker="家庭行程" title="一起規劃下一站" copy="建立屬於家人的第一段旅程。" action={<button className="button primary" onClick={create}>＋ 新增行程</button>} /><section className="setting-card"><label>行程名稱<input value={title} onChange={e => setTitle(e.target.value)} placeholder="例如：週末旅行" /></label><div className="profile-grid"><label>開始日期<input type="date" value={start} onChange={e => setStart(e.target.value)} /></label><label>結束日期<input type="date" value={end} onChange={e => setEnd(e.target.value)} /></label></div></section><div className="thread-list">{items.length ? items.map(item => <article className="thread-card" key={item.id}><div className="thread-marker forest">↗</div><div className="thread-body"><h3>{item.title}</h3><p>{item.start_date} ～ {item.end_date}</p></div></article>) : <div className="empty-state"><p>{sessionEmail ? '目前沒有行程資料。' : '登入後即可查看家庭行程。'}</p></div>}</div></> }
function Albums({ notify, sessionEmail }: { notify: (m: string) => void; sessionEmail: string | null }) { const [items, setItems] = useState<Array<{ id: string; title: string; created_at: string }>>([]); const [title, setTitle] = useState(''); const load = async () => { if (!supabase || !sessionEmail) return; const { data } = await supabase.from('albums').select('id,title,created_at').order('created_at', { ascending: false }); setItems(data ?? []) }; useEffect(() => { load() }, [sessionEmail]); const create = async () => { if (!supabase || !sessionEmail) { notify('請先登入會員'); return } if (!title.trim()) { notify('請輸入相簿名稱'); return } const { data: { user } } = await supabase.auth.getUser(); if (!user) return; const { data: profile } = await supabase.from('profiles').select('family_id').eq('id', user.id).maybeSingle(); if (!profile?.family_id) { notify('會員資料尚未同步'); return } const { error } = await supabase.from('albums').insert({ family_id: profile.family_id, title: title.trim() }); if (error) notify(error.message); else { setTitle(''); notify('相簿已建立'); load() } }; return <><Hero kicker="共享相簿" title="收藏小日子" copy="把家人想留下的每個時刻放在一起。" action={<button className="button primary" onClick={create}>＋ 新增相簿</button>} /><section className="setting-card"><label>相簿名稱<input value={title} onChange={e => setTitle(e.target.value)} placeholder="例如：家庭聚會" /></label></section><div className="album-grid">{items.length ? items.map(item => <article className="album-card" key={item.id}><div className="album-art tile-0"><span>吾黨所鍾</span></div><div className="album-caption"><b>{item.title}</b><small>{new Date(item.created_at).toLocaleDateString('zh-TW')}</small></div></article>) : <div className="empty-state"><p>{sessionEmail ? '目前沒有相簿資料。' : '登入後即可查看共享相簿。'}</p></div>}</div></> }
function Profile({ notify, saveProfile, sessionName, sessionEmail }: { notify: (m: string) => void; saveProfile: (name: string) => void; sessionName: string; sessionEmail: string | null }) { const [name, setName] = useState(sessionName); useEffect(() => setName(sessionName), [sessionName]); return <><section className="profile-hero"><div className="avatar avatar-profile">{name ? name[0] : '訪'}</div><div><p className="eyebrow">你的個人檔案</p><h1>{name || '尚未登入'}<span>.</span></h1><p className="hero-copy">{sessionEmail ?? '登入後即可編輯你的個人資料。'}</p></div></section><div className="profile-grid"><section className="setting-card"><p className="eyebrow">個人資料</p><label>顯示名稱<input value={name} onChange={(e) => setName(e.target.value)} placeholder="登入後設定名稱" /></label><button className="button primary" onClick={() => saveProfile(name)}>儲存變更</button></section><section className="setting-card accent"><p className="eyebrow">家庭資料</p><h3>吾黨所鍾</h3><p className="muted">所有會員共享同一個家庭空間，討論內容會即時保存。</p><button className="text-button" onClick={() => notify(sessionEmail ? '家庭資料已同步' : '請先登入會員')}>{sessionEmail ? '已連接 ↗' : '登入會員 ↗'}</button></section></div></> }

function _RichTextEditor({ value, onChange, placeholder }: { value: string; onChange: (value: string) => void; placeholder?: string }) {
  const ref = useState<HTMLTextAreaElement | null>(null)
  const format = (prefix: string, suffix = prefix) => { const node = ref[0]; if (!node) return; const start = node.selectionStart; const end = node.selectionEnd; const selected = value.slice(start, end) || '文字'; onChange(`${value.slice(0, start)}${prefix}${selected}${suffix}${value.slice(end)}`); requestAnimationFrame(() => node.focus()) }
  return <div className="rich-editor"><div className="editor-toolbar"><button type="button" onClick={() => format('**')}><b>B</b></button><button type="button" onClick={() => format('*')}><i>I</i></button><button type="button" onClick={() => format('- ', '')}>☷</button><button type="button" onClick={() => format('> ', '')}>❝</button><span>{value.length} 字</span></div><textarea ref={node => { if (node) ref[1](node) }} value={value} onChange={event => onChange(event.target.value)} placeholder={placeholder} /></div>
}

export default App



// @ts-nocheck
